### ISSUE TITLE
Kind and Member are not exported (vCard 4)

### ISSUE THREAD

**Issue by Ypot** [pinoaffe/org-vcard#41]
When 
:KIND: group 

it should export
:MEMBER: (ex. mailto:xxx)

Using KIND allows us to have an Enterprise as a contact, and to add to it the mail of people who work there (MEMBER).

https://datatracker.ietf.org/doc/html/rfc6350#section-6.1.4
https://datatracker.ietf.org/doc/html/rfc6350#section-6.6.5

**Comment by Ypot** [comment]
Note: ok, I can see now that it is customizable :-)

**Comment by pinoaffe** [comment]
mappings between vCard and Org are indeed customizable (by creating custom "styles"), so I'm closing this issue
